# Service
apiVersion: v1
kind: Service
metadata:
  name: nestkube
spec:
  selector:
    app: nestkube
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  # type: ClusterIP
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestkube
  template:
    metadata:
      labels:
        app: nestkube
    spec:
      containers:
        - name: app
          # image: usuario/imagen:1.0.0
          image: metrics
          ports:
            - containerPort: 3000
          # imagePullPolicy: Always
          imagePullPolicy: Never
